sonar.projectKey=express-api
sonar.projectName=Express API
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000

sonar.login=sqa_1b7d968443939b596f3c1ae7b1ac48beb8c89fc1

sonar.exclusions=node_modules/**,.vscode/**,coverage/**,k8s/**